source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3', '~> 1.3.7'
gem 'rabl', '~> 0.8.6'
gem 'requirejs-rails', :git => 'git://github.com/jwhitley/requirejs-rails'
gem 'taglib-ruby', '~> 0.5.2'
gem 'lastfm', '~> 1.19.0'
#gem 'delayed_job_active_record', '~> 0.4.4'
gem 'daemons', '~> 1.1.9'
gem 'mysql2', '~> 0.3.11'
gem 'will_paginate', '~> 3.0.4'
gem 'fog', '~> 1.14.0'

gem 'sass-rails',   '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier', '~> 2.1.2'
