paths:
    jquery: "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery"
    "jquery.bootstrap": "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.2/js/bootstrap"
    handlebars: "https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.0.0/handlebars"
    notifier: "https://raw.github.com/papodaca/Notifier.js/master/Notifier"
    backbone: "https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.0.0/backbone"
    "backbone.pageable": "https://cdnjs.cloudflare.com/ajax/libs/backbone-pageable/1.3.1/backbone-pageable"
    underscore: "https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.0/underscore"
    json2: "https://cdnjs.cloudflare.com/ajax/libs/json2/20121008/json2"
    hbs: "https://raw.github.com/epeli/requirejs-hbs/master/hbs"
    text: "https://cdnjs.cloudflare.com/ajax/libs/require-text/2.0.5/text"
shim:
    backbone:
        deps: [ "jquery", "underscore" ]
        exports: "Backbone"
    underscore:
        exports: "_"
    "backbone.pageable":
        deps: [ "backbone" ]
        exports: "Backbone"
    "jquery.bootstrap":
        deps: ["jquery"]
        exports: "jQuery"
    handlebars:
        exports: "Handlebars"
