paths:
    jquery: "vendor/jquery"
    "jquery.bootstrap": "vendor/bootstrap"
    handlebars: "vendor/handlebars"
    notifier: "vendor/notifier"
    backbone: "vendor/backbone"
    underscore: "vendor/underscore"
    json2: "vendor/json2"
    hbs: "vendor/hbs"
    text: "vendor/text"
shim:
    "jquery.bootstrap":
        deps: ["jquery"]
        exports: "jquery"
    notifier:
        exports: "Notifier"
