# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#

Role.delete_all
Roles = Role.create([
  {name: 'Admin', level: 0},
  {name: 'User', level: 10},
  {name: 'Guest', level: 20}
])

MediaType.delete_all
MediaTypes = MediaType.create([
  {mime_type: 'audio/aiff', extension: 'aif'},
  {mime_type: 'audio/aiff', extension: 'aifc'},
  {mime_type: 'audio/aiff', extension: 'aiff'},
  {mime_type: 'audio/mpeg', extension: 'mp3'},
  {mime_type: 'audio/ogg', extension: 'ogg'},
  {mime_type: 'audio/wav', extension: 'wav'},
  {mime_type: 'audio/x-flac', extension: 'flac'},
  {mime_type: 'audio/aac', extension: 'm4a'},
  {mime_type: 'audio/aac', extension: 'aac'},
  {mime_type: 'audio/aac', extension: '3gp'},
  {mime_type: 'audio/basic', extension: 'au'},
  {mime_type: 'audio/x-ms-wma', extension: 'wma'},
  {mime_type: 'audio/x-monkeys-audio', extension: 'ape'},
  {mime_type: 'image/jpeg', extension: 'jpg'},
  {mime_type: 'image/jpeg', extension: 'jpeg'},
  {mime_type: 'image/png', extension: 'png'},
  {mime_type: 'image/gif', extension: 'gif'},
  {mime_type: 'application/rss+xml', extension: 'rss'},
  {mime_type: 'application/rss+xml', extension: 'xml'},
  {mime_type: 'application/atom+xml', extension: 'atom'},
  {mime_type: 'application/atom+xml', extension: 'xml'}
])

Genre.delete_all
Genres = Genre.create([
  {name: 'Blues'},
  {name: 'Classic Rock'},
  {name: 'Country'},
  {name: 'Dance'},
  {name: 'Disco'},
  {name: 'Funk'},
  {name: 'Grunge'},
  {name: 'Hip-Hop'},
  {name: 'Jazz'},
  {name: 'Metal'},
  {name: 'New Age'},
  {name: 'Oldies'},
  {name: 'Other'},
  {name: 'Pop'},
  {name: 'R&B'},
  {name: 'Rap'},
  {name: 'Reggae'},
  {name: 'Rock'},
  {name: 'Techno'},
  {name: 'Industrial'},
  {name: 'Alternative'},
  {name: 'Ska'},
  {name: 'Death Metal'},
  {name: 'Pranks'},
  {name: 'Soundtrack'},
  {name: 'Euro-Techno'},
  {name: 'Ambient'},
  {name: 'Trip-Hop'},
  {name: 'Vocal'},
  {name: 'Jazz+Funk'},
  {name: 'Fusion'},
  {name: 'Trance'},
  {name: 'Classical'},
  {name: 'Instrumental'},
  {name: 'Acid'},
  {name: 'House'},
  {name: 'Game'},
  {name: 'Sound Clip'},
  {name: 'Gospel'},
  {name: 'Noise'},
  {name: 'AlternRock'},
  {name: 'Bass'},
  {name: 'Soul'},
  {name: 'Punk'},
  {name: 'Space'},
  {name: 'Meditative'},
  {name: 'Instrumental Pop'},
  {name: 'Instrumental Rock'},
  {name: 'Ethnic'},
  {name: 'Gothic'},
  {name: 'Darkwave'},
  {name: 'Techno-Industrial'},
  {name: 'Electronic'},
  {name: 'Pop-Folk'},
  {name: 'Eurodance'},
  {name: 'Dream'},
  {name: 'Southern Rock'},
  {name: 'Comedy'},
  {name: 'Cult'},
  {name: 'Gangsta'},
  {name: 'Top 40'},
  {name: 'Christian Rap'},
  {name: 'Pop/Funk'},
  {name: 'Jungle'},
  {name: 'Native American'},
  {name: 'Cabaret'},
  {name: 'New Wave'},
  {name: 'Psychadelic'},
  {name: 'Rave'},
  {name: 'Showtunes'},
  {name: 'Trailer'},
  {name: 'Lo-Fi'},
  {name: 'Tribal'},
  {name: 'Acid Punk'},
  {name: 'Acid Jazz'},
  {name: 'Polka'},
  {name: 'Retro'},
  {name: 'Musical'},
  {name: 'Rock & Roll'},
  {name: 'Hard Rock'},
  {name: 'Folk'},
  {name: 'Folk-Rock'},
  {name: 'National Folk'},
  {name: 'Swing'},
  {name: 'Fast Fusion'},
  {name: 'Bebob'},
  {name: 'Latin'},
  {name: 'Revival'},
  {name: 'Celtic'},
  {name: 'Bluegrass'},
  {name: 'Avantgarde'},
  {name: 'Gothic Rock'},
  {name: 'Progressive Rock'},
  {name: 'Psychedelic Rock'},
  {name: 'Symphonic Rock'},
  {name: 'Slow Rock'},
  {name: 'Big Band'},
  {name: 'Chorus'},
  {name: 'Easy Listening'},
  {name: 'Acoustic'},
  {name: 'Humour'},
  {name: 'Speech'},
  {name: 'Chanson'},
  {name: 'Opera'},
  {name: 'Chamber Music'},
  {name: 'Sonata'},
  {name: 'Symphony'},
  {name: 'Booty Bass'},
  {name: 'Primus'},
  {name: 'Porn Groove'},
  {name: 'Satire'},
  {name: 'Slow Jam'},
  {name: 'Club'},
  {name: 'Tango'},
  {name: 'Samba'},
  {name: 'Folklore'},
  {name: 'Ballad'},
  {name: 'Power Ballad'},
  {name: 'Rhythmic Soul'},
  {name: 'Freestyle'},
  {name: 'Duet'},
  {name: 'Punk Rock'},
  {name: 'Drum Solo'},
  {name: 'A capella'},
  {name: 'Euro-House'},
  {name: 'Dance Hall'}
])